<a href="https://colab.research.google.com/github/mistermunga/ml101/blob/main/ML_24_01_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.random.seed(0)
x1 = np.random.randint(10, size = 8)
x1

array([5, 0, 3, 3, 7, 9, 3, 5])

In [ ]:
x2 = np.random.randint(10, size = (5, 6))
x2


array([[2, 4, 7, 6, 8, 8],
       [1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3],
       [0, 3, 5, 0, 2, 3],
       [8, 1, 3, 3, 3, 7]])

In [ ]:
x1[0]

5

In [ ]:
x1[-2:]

array([3, 5])

In [ ]:
x2[:-1, -1:]

array([[8],
       [1],
       [3],
       [3]])

In [ ]:
x2[4, 1]

1

In [ ]:
grid = np.arange(9).reshape(3,3)
grid

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x1.reshape(2, 4)

array([[5, 0, 3, 3],
       [7, 9, 3, 5]])

In [ ]:
x2.shape

(5, 6)

In [ ]:
x = np.arange(5)

In [ ]:
x[np.newaxis,:]  # row vector

array([[0, 1, 2, 3, 4]])

In [ ]:
x[:, np.newaxis]  # column vector

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
x = np.arange(1, 11)

x[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
x[1::2]

array([ 2,  4,  6,  8, 10])

In [ ]:
x[4:] = 0
x

array([1, 2, 3, 4, 0, 0, 0, 0, 0, 0])

In [ ]:
grid = np.arange(1, 31).reshape(6, 5)

grid

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
grid[:3,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
grid[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [ ]:
grid[::, ::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21],
       [30, 29, 28, 27, 26]])

In [ ]:
grid[:, 2:3]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23],
       [28]])

In [ ]:
x8 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

x8.T

(5, 2)

In [ ]:
grid2 = np.arange(31, 61).reshape(6, 5)

grid2

array([[31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]])

In [ ]:
np.concatenate((grid, grid2), axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]])